### ISSUE TITLE
AliceOS v3.0.0 Roadmap

### ISSUE THREAD

**Issue by alicerunsonfedora** [ProjectAliceDev/aliceos#25]
The following issue is a meta-post containing the feature and improvement wishlist for AliceOS v3.0.0 (name TBD). AliceOS v3.0.0 will continue to build off of the existing work done in AliceOS Prospect Park (v2.0.0) while adding new features for both users and developers. This issue will be closed once all feature requests have been created into separate issues and been resolved, respectively.

The original issue hosted on YouTrack can be found by [clicking here](https://youtrack.marquiskurt.net/youtrack/issue/AOS-1).

- [ ] **Desktop improvements**: Add more improvements to the existing Desktop core service experience.
  - [ ] **App launcher**: A Dock-like app launcher that comes bundled with the Desktop that can be attached to any Ren'Py screen or be quickly accessible with a button like the [quick inventory view in Inventories](https://docs.aliceos.app/System/07-inventories/#using-the-hud).
  - [ ] **Context menus on Activities icons**: Allow users to right-click on an icon to show a context menu that will allow some actions, such as adding an app to the app launcher.
  - [ ] **Set custom wallpaper**: Add preferences for the Desktop that allow changing the desktop wallpaper rather than using Ren'Py `init` overrides to change the wallpaper.
- [ ] **Expansion of ScreenKit**: Add more screen styles to ScreenKit such as tab groups, icons, etc.
- [ ] **Poetry compatibility**: Updating the codebase to be compatible with the [Poetry](https://python-poetry.org) package management system.
    - [ ] **PyPI support**: Add support for installing AliceOS via PyPI (?).
- [ ] **InventoryKit**: Migrate existing Inventories functionality to its own dedicated framework and rebuild Inventories on top of it.
  - [ ] **Inventory access**: Add permissions for AliceOS apps to access and manage the inventory.
- [ ] **User support**: Add ability to create and manage users.
  - [ ] **File system**: Create a file system in the Ren'Py save directory that will host files for users, accessible by AliceOS apps and core services ([permission functionality for this exists](https://docs.aliceos.app/Develop-Apps/01-manifest/#declaring-permissions)).
  - [ ] **Updated Desktop preferences**: Preferences for Desktop settings can be stored per-user, and interface elements can be added for that user.
- [ ] **AppKit improvements**: Add more improvements to the AppKit framework for developing third-party apps for AliceOS.
  - [ ] **App manifest markup**: Create a system that can read app manifest properties from a markup file instead of directly modifying the `ASAppRepresentative` class, either as a JSON, YML, or TOML file.
  - [ ] **Add better IDE support**: Make Python functions in AliceOS classes accessible to IDEs and text editors.
  - [ ] **App generation utility**: Create a basic utility that will generate apps interactively, similar to the VS Code extension generator with Yeoman.
